### ISSUE TITLE
[cetic/zabbix] official helmchart integration / merge

### ISSUE THREAD

**Issue by richard-ostrochovsky** [cetic/helm-zabbix#42]
hello, this is not standard "feature request" (and not an issue at all :) ), but Zabbix itself is currently releasing its helm chart https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/, which contains only following components, being helm-installed into K8S:

- **zabbix-proxy-sqlite3** (as ReplicaSet)
- **zabbix-agent2** (as DaemonSet)
- **kube-state-metrics** (as ReplicaSet)

to be working in tandem with new OOB templates for monitoring K8S:
https://www.zabbix.com/documentation/devel/en/manual/introduction/whatsnew600#kubernetes

it does not contain ZBX server, which is meaningful in standard cases, as ZBX server should be independent on such dynamic infrastructure as K8S is, to monitor it reliably, not to be influenced by K8S dynamics ...

maybe this new development could be integrated somehow into cetic/helm-zabbix (e.g. as git submodule?), not to duplicate the same functionality, just adding something, when still needed ... maybe these two zabbix-helm projects and their efforts could be joint into one, as "together everyone achieves more (t.e.a.m.)" :)

we are currently migrating from cetic/helm-zabbix to "official" helmchart, being the next evolutionary step to support new OOB monitoring of K8S - but I am very thankful, that helm-zabbix was available sooner, so we could use it successfully - thank you very much for that!

**Comment by aeciopires** [comment]
Hello @richard-ostrochovsky!

1- Thank you very much for sharing your experience using chart **cetic/helm-zabbix**. It's great to know that the volunteer work of some people was able to help you. This is the main purpose of an Open Source and free project.

2- It's great to know that Zabbix SIA is finally developing an official helm chart to install Zabbix components. On 03/01/2020 I opened [this issue](https://support.zabbix.com/browse/ZBXNEXT-5787). The **cetic/helm-zabbix** chart will be kept until the official Zabbix chart is ready or as long as people want to keep it. But for technical reasons, it's always good to use the official chart of those who develop Zabbix because they have all the technical expertise.

3- I would like to join efforts between the two projects and collaborate on the official chart, but I didn't get an answer... I tried to access the official git repository and I don't have access, I think it's read-only... this subject will be most welcome.

> ERROR to reset password to access https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/browse repository
> Bitbucket is unable to reset the password for your account because it is managed by a read-only external directory. Please contact your administrator to change your password. If you did not request a new password, you don't need to take any further action and can safely disregard this email.


Again thank you very much! Have a nice week and if I can help with anything, just let me know.

**Comment by banzo** [comment]
I just voted for the issue in Jira, and added a backlink to this issue.

I wonder why they did not jump the Helm chart step and go the [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) route directly.

**Comment by richard-ostrochovsky** [comment]
Hello guys, thank you for your positive feedback.

Additional information:

Master ticket for OOB monitoring of K8S:
https://support.zabbix.com/browse/ZBXNEXT-4635

Its subticket covering new helmchart:
https://support.zabbix.com/browse/ZBXNEXT-6933

I currently posted some ideas about its further advancement there, but as I am still not a helm-expert-type-of-guy :) (but still better than when I was last time we were in touch last year :) ), maybe you guys would have more relevant suggestions about it than just me.

**Comment by richard-ostrochovsky** [comment]
Hello @aeciopires , I would like to share with you several ideas about potential alingnment and further advancements of cetic/helm-zabbix:

- **ZBX proxies and agents** could be removed from cetic/helm-zabbix completely, as as I see it, they are now with ZBX official helm chart redundant (in fact, I am currently trying to remove them from our setup, because although I already replaced some parts of our cetic/helm-zabbix monitoring with official, we will keep ZBX server part some more time, unless not deteached from K8S completely, but without redundant proxy+agent)

- about **ZBX server (+DB+frontend)**, although it is architectonic question per particular deployment, if to have it inside K8S cluster (variant 1) or outside/independent of it (variant 2), but if variant 1 realized, maybe this new ZBX 6.0 **high availability** possibility could be incorporated somehow into cetic/helm-zabbix: https://www.zabbix.com/documentation/6.0/en/manual/concepts/server/ha

**Comment by aeciopires** [comment]
Hello @richard-ostrochovsky!

With this Pull Request, installation of all components is optional with chart cetic/zabbix. I think it's better that way because everyone can decide what to install and how to install it (whether using this chart or the official chart). Do you agree with this approach?

About Zabbix's HA support, I don't have the expertise and I don't have a test environment to do this. But it would be really nice if you or someone else could open a Pull Request implementing this.
