### ISSUE TITLE
[cetic/zabbix] issue title

### ISSUE THREAD

**Issue by aeciopires** [cetic/helm-zabbix#45]
**Describe the bug**

Hello @banzo!

Can you help fix this issue in helm chart publishing? 

https://app.circleci.com/pipelines/github/cetic/helm-zabbix/75/workflows/8a3d915f-664e-40d5-a73a-0bbe645a9d63/jobs/67

```
[gh-pages c6a3b96] Published by CircleCI https://circleci.com/gh/cetic/helm-zabbix/67
 2 files changed, 219 insertions(+), 185 deletions(-)
 create mode 100644 zabbix/zabbix-1.0.0.tgz
ERROR: Permission to cetic/helm-charts.git denied to alexnuttinck.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**What happened**:

Problem to publish helm charts.

**What you expected to happen**:

Publish helm chart in gh-pages.

**Comment by alexnuttinck** [comment]
Hello @aeciopires,

My ssh key has been revoked as I am no more in the cetic organization.

@banzo (hello :wave:) check at the doc here: https://github.com/cetic/helm-chart-publisher.
You need to add your ssh Key in Circle CI (Project settings > SSH Key > Add SSH Key) in order to be able to clone and commit on the Helm charts repo.

**Comment by banzo** [comment]
The build is fixed, thanks @alexnuttinck :wave:
